/* Wirepas Oy licensed under Apache License, Version 2.0
 *
 * See file LICENSE for full license details.
 *
 */

// clang-format off

#ifndef WPC_CONSTANTS_H__
#define WPC_CONSTANTS_H__

/* Constant to get the corresponding confirm/response from a given request/indication */
#define SAP_CONFIRM_OFFSET     0x80
#define SAP_RESPONSE_OFFSET    SAP_CONFIRM_OFFSET

/*
 * Data Service Access Points
 */
#define DSAP_DATA_TX_REQUEST                   0x01
#define DSAP_DATA_TX_CONFIRM                   (SAP_CONFIRM_OFFSET + DSAP_DATA_TX_REQUEST)
#define DSAP_DATA_TX_TT_REQUEST                0x1F
#define DSAP_DATA_TX_TT_CONFIRM                (SAP_CONFIRM_OFFSET + DSAP_DATA_TX_TT_REQUEST)
#define DSAP_DATA_TX_INDICATION                0x02
#define DSAP_DATA_TX_RESPONSE                  (SAP_RESPONSE_OFFSET + DSAP_DATA_TX_INDICATION)
#define DSAP_DATA_RX_INDICATION                0x03
#define DSAP_DATA_RX_RESPONSE                  (SAP_RESPONSE_OFFSET + DSAP_DATA_RX_INDICATION)

/*
 * Management Service Access Points
 */
#define MSAP_INDICATION_POLL_REQUEST           0X04
#define MSAP_INDICATION_POLL_CONFIRM           (SAP_CONFIRM_OFFSET + MSAP_INDICATION_POLL_REQUEST)
#define MSAP_STACK_START_REQUEST               0x05
#define MSAP_STACK_START_CONFIRM               (SAP_CONFIRM_OFFSET + MSAP_STACK_START_REQUEST)
#define MSAP_STACK_STOP_REQUEST                0x06
#define MSAP_STACK_STOP_CONFIRM                (SAP_CONFIRM_OFFSET + MSAP_STACK_STOP_REQUEST)
#define MSAP_STACK_STATE_INDICATION            0x07
#define MSAP_STACK_STATE_RESPONSE              (SAP_RESPONSE_OFFSET + MSAP_STACK_STATE_INDICATION)
#ifdef LEGACY_APP_CONFIG
// For legacy support for firmware <= 3.1
#define MSAP_APP_CONFIG_DATA_WRITE_REQUEST     0x08
#define MSAP_APP_CONFIG_DATA_WRITE_CONFIRM     (SAP_CONFIRM_OFFSET + MSAP_APP_CONFIG_DATA_WRITE_REQUEST)
#define MSAP_APP_CONFIG_DATA_READ_REQUEST      0x09
#define MSAP_APP_CONFIG_DATA_READ_CONFIRM      (SAP_CONFIRM_OFFSET + MSAP_APP_CONFIG_DATA_READ_REQUEST)
#define MSAP_APP_CONFIG_DATA_RX_INDICATION     0x0A
#define MSAP_APP_CONFIG_DATA_RX_RESPONSE       (SAP_RESPONSE_OFFSET + MSAP_APP_CONFIG_DATA_RX_INDICATION)
#else
#define MSAP_APP_CONFIG_DATA_WRITE_REQUEST     0x3A
#define MSAP_APP_CONFIG_DATA_WRITE_CONFIRM     (SAP_CONFIRM_OFFSET + MSAP_APP_CONFIG_DATA_WRITE_REQUEST)
#define MSAP_APP_CONFIG_DATA_READ_REQUEST      0x3B
#define MSAP_APP_CONFIG_DATA_READ_CONFIRM      (SAP_CONFIRM_OFFSET + MSAP_APP_CONFIG_DATA_READ_REQUEST)
#define MSAP_APP_CONFIG_DATA_RX_INDICATION     0x3F
#define MSAP_APP_CONFIG_DATA_RX_RESPONSE       (SAP_RESPONSE_OFFSET + MSAP_APP_CONFIG_DATA_RX_INDICATION)
#endif // LEGACY_APP_CONFIG
#define MSAP_ATTRIBUTE_WRITE_REQUEST           0x0B
#define MSAP_ATTRIBUTE_WRITE_CONFIRM           (SAP_CONFIRM_OFFSET + MSAP_ATTRIBUTE_WRITE_REQUEST)
#define MSAP_ATTRIBUTE_READ_REQUEST            0x0C
#define MSAP_ATTRIBUTE_READ_CONFIRM            (SAP_CONFIRM_OFFSET + MSAP_ATTRIBUTE_READ_REQUEST)
#define MSAP_SCRATCH_START_REQUEST             0x17
#define MSAP_SCRATCH_START_CONFIRM             (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_START_REQUEST)
#define MSAP_SCRATCH_BLOCK_REQUEST             0x18
#define MSAP_SCRATCH_BLOCK_CONFIRM             (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_BLOCK_REQUEST)
#define MSAP_SCRATCH_STATUS_REQUEST            0x19
#define MSAP_SCRATCH_STATUS_CONFIRM            (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_STATUS_REQUEST)
#define MSAP_SCRATCH_UPDATE_REQUEST            0x1A
#define MSAP_SCRATCH_UPDATE_CONFIRM            (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_BOOTABLE_REQUEST)
#define MSAP_SCRATCH_CLEAR_REQUEST             0x1B
#define MSAP_SCRATCH_CLEAR_CONFIRM             (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_CLEAR_REQUEST)
#define MSAP_SCRATCH_REMOTE_STATUS_REQUEST     0x1C
#define MSAP_SCRATCH_REMOTE_STATUS_CONFIRM     (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_REMOTE_STATUS_REQUEST)
#define MSAP_SCRATCH_REMOTE_STATUS_INDICATION  0x1D
#define MSAP_SCRATCH_REMOTE_STATUS_RESPONSE    (SAP_RESPONSE_OFFSET + MSAP_SCRATCH_REMOTE_STATUS_INDICATION)
#define MSAP_SCRATCH_REMOTE_UPDATE_REQUEST     0x1E
#define MSAP_SCRATCH_REMOTE_UPDATE_CONFIRM     (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_REMOTE_UPDATE_REQUEST)
#define MSAP_GET_NBORS_REQUEST                 0x20
#define MSAP_GET_NBORS_CONFIRM                 (SAP_CONFIRM_OFFSET + MSAP_GET_NBORS_REQUEST)
#define MSAP_SCAN_NBORS_REQUEST                0x21
#define MSAP_SCAN_NBORS_CONFIRM                (SAP_CONFIRM_OFFSET + MSAP_SCAN_NBORS_REQUEST)
#define MSAP_SCAN_NBORS_INDICATION             0x22
#define MSAP_SCAN_NBORS_RESPONSE               (SAP_RESPONSE_OFFSET + MSAP_SCAN_NBORS_INDICATION)
#define MSAP_SINK_COST_WRITE_REQUEST           0x38
#define MSAP_SINK_COST_WRITE_CONFIRM           (SAP_CONFIRM_OFFSET + MSAP_SINK_COST_WRITE_REQUEST)
#define MSAP_SINK_COST_READ_REQUEST            0x39
#define MSAP_SINK_COST_READ_CONFIRM            (SAP_CONFIRM_OFFSET + MSAP_SINK_COST_READ_REQUEST)
#define MSAP_SCRATCH_TARGET_WRITE_REQUEST      0x26
#define MSAP_SCRATCH_TARGET_WRITE_CONFIRM      (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_TARGET_WRITE_REQUEST)
#define MSAP_SCRATCH_TARGET_READ_REQUEST       0x27
#define MSAP_SCRATCH_TARGET_READ_CONFIRM       (SAP_CONFIRM_OFFSET + MSAP_SCRATCH_TARGET_READ_REQUEST)

/*
 * Configuration Service Access Points
 */
#define CSAP_ATTRIBUTE_WRITE_REQUEST           0x0D
#define CSAP_ATTRIBUTE_WRITE_CONFIRM           (SAP_CONFIRM_OFFSET + CSAP_ATTRIBUTE_WRITE_REQUEST)
#define CSAP_ATTRIBUTE_READ_REQUEST            0x0E
#define CSAP_ATTRIBUTE_READ_CONFIRM            (SAP_CONFIRM_OFFSET + CSAP_ATTRIBUTE_READ_REQUEST)
#define CSAP_FACTORY_RESET_REQUEST             0x16
#define CSAP_FACTORY_RESET_CONFIRM             (SAP_CONFIRM_OFFSET + CSAP_FACTORY_RESET_REQUEST)

/* Maximum number of endpoint */
#define MAX_NUMBER_EP    256

/* Maximun sent packet with indication */
#define MAX_SENT_PACKET_WITH_INDICATION    16

/* Maximun PDU size for all platforms */
#define MAX_DATA_PDU_SIZE    102


#endif

// clang-format on
