# Sources for WPC module
WPC_MODULE = $(SOURCEPREFIX)wpc/

SOURCES += $(WPC_MODULE)wpc.c
SOURCES += $(WPC_MODULE)slip.c
SOURCES += $(WPC_MODULE)wpc_internal.c
SOURCES += $(WPC_MODULE)dsap.c
SOURCES += $(WPC_MODULE)msap.c
SOURCES += $(WPC_MODULE)csap.c
SOURCES += $(WPC_MODULE)attribute.c

CFLAGS  += -I$(WPC_MODULE)include/